"""empty message

Revision ID: 64bcc4eef5b5
Revises: 461ca220d13f
Create Date: 2023-04-15 17:20:29.207576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bcc4eef5b5'
down_revision = '461ca220d13f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
